### ISSUE TITLE
Add library to CocoaPods

### ISSUE THREAD

**Issue by donbe** [zoul/Lambda-Alert#6]
Better able to add to CocoaPods~
https://github.com/CocoaPods/CocoaPods

**Comment by zoul** [comment]
There’s already a podspec in the repository contributed by @brandondean, is it broken? (Or is something else needed to make CocoaPods work? I don’t use it, so I have no idea.)

**Comment by jcoleman** [comment]
Basically, the podspec needs to be added to the CocoaPods/Specs repository, and the podspec both in this repo and the CocoaPods/Specs repo needs to be updated when you release a new version (and update the version number.)

Having the spec in the CocoaPods/Specs repo allows people to use it without having to know that this repository is where it is (and it will be listed in the CocoaPods search tool.

See: http://cocoapods.org/#get_started

Edit: You'll also want the podspec file to reference the repo by tags (and add a tag to the repo when each version is released.) If you need any help getting this all set up, feel free to ping me with any questions.

**Comment by zoul** [comment]
Thanks to @jcoleman this is already happening, see #7.
